# -*- coding: utf-8 -*-
"""study_material_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wGmrZEOgu08DmGDG4ty9oegn-3MQ3j-y
"""

# Python Introductory Study Material

"""Python was released in 1991 by Guido van Rossum

Python Syntax compared to other programming languages

Python has some similarities to the English language.
Uses a new line to complete a command. It doesn't use semicolons or parentheses like C++ or Java.
Relies on indentation using withespace. Whitespaces in Python are used to define the scope for loops, functions and classes. Other programming languages use curly-brakes for this but that's not the case for Python.

Python is an interpreted programming language.
"""

print("Hello, World!")

"""Indentation in Python

Indentation is the spaces at the beginning of each line of code.
It is very important in Python because it indicates blocks of code.
In other languages indentations is mostly for code readability but in Pyton is more than that. It defines the code blocks for loops, functions and classes.
"""

# No indentation gives an error
if 5 > 2:
print("Five is greater than two!")

# To correct the previous error use indentation
# One space indentation
if 9 == 9:
 print("Nine is equal to nine!")

# Two spaces indentation
if 9 == 9:
  print("Nine is equal to nine!")

# Three spaces indentation
if 9 == 9:
   print("Nine is equal to nine!")


# Four spaces indentation
if 9 == 9:
    print("Nine is equal to nine!")

# Five spaces indentation
if 9 == 9:
     print("Nine is equal to nine!")

# Six spaces indentation
if 9 == 9:
      print("Nine is equal to nine!")

# Bad indentation.
# This will give an error because the number of spaces 
# in the indentation for the same block must be the same
# You need to use the same number of indentation spaces for the same block

if 9 == 9:
 print("Nine is equal to nine!")
        print("Nine is equal to nine!")

# To correct the previous error 
# Use the same indentation for the same block of code
if 9 == 9:
 print("Nine is equal to nine!")
 print("Nine is equal to nine!")