# -*- coding: utf-8 -*-
"""study_material_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1peHbfhTilCsAl7ghQKLk29A0i6zqnI5z
"""

# Python Introductory Study Material
# Topics: Comments, Variables

"""Comments can be used to explain Python code.

Comments can be used to make the code more readable.

Comments can be used to prevent execution when testing code.
"""



"""In any computer language, a variable represents a value that can change during the program execution.

In some programming languages variables require an initial declarationa and a type association before they can be used in the program. That is not the case with Python. In Python, variables do not need to be declared or be assigned a type before they can be used. Variables in Python are created when you assign a value to them.
"""

a = 100 # holds an integer value
b = 3.1416 # holds a type value
c = 'c' # holds a character value
d = 'Hello, World!' # holds a string
e = True # holds a boolean value

# print variables
print( a, b, c, d, e)

# Assign new values to the variables
a, b, c, d, e = 400, 20.35, 'e', 'Nice to meet you!', False

# print variables again
print( a, b, c, d, e)

