# -*- coding: utf-8 -*-
"""study_material_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1peHbfhTilCsAl7ghQKLk29A0i6zqnI5z
"""

# Python Introductory Study Material
# Topics: Comments, Variables

# Comments in Python

"""Comments are text used to explain the purpose and logic of the code we write. Their function is to make the code more readable. Also, comments are used when we are testing code, if we mark code as comments, it will not execute during runtime."""

#This is a comment in Python
print("Hello, World!")

print("Hello, World!") #This is also a comment in Python

# When we comment out Python code, it will not execute when we run the program
#print("Hello, World!")
print("Enjoy Python Programming!")

"""
Multiline comments or multiline strings
are comments that are written in more than one line.
It is similar to a paragraph.
"""
'''
Python ignores strings that are not
assigned to a variable.
'''
"""
Hence, a string not assigned to a variable
becomes a multiline comment in Python.
"""
print("Hello, World!")

# Variables in Python

"""In any computer language, a variable represents a value that can change during the program execution.

In some programming languages variables require an initial declarationa and a type association before they can be used in the program. That is not the case with Python. In Python, variables do not need to be declared or be assigned a type before they can be used. Variables in Python are created when you assign a value to them.
"""

a = 100 # holds an integer value
b = 3.1416 # holds a type value
c = 'c' # holds a character value
d = 'Hello, World!' # holds a string
e = True # holds a boolean value

# print variables
print( a, b, c, d, e)

# Variables in Python are case-sensitive
a = 3
A = 9
print (a, A)

# In the case of string variables they can be declared using single or double quotes

a = "Ana"
b = 'Alejandro'

c = 'Luisa'
# and
c = "Luisa"
# will give the same results

# Assign new values to the variables
a, b, c, d, e = 400, 20.35, 'e', 'Nice to meet you!', False

# print variables again
print( a, b, c, d, e)

# Remember that Python has no command for declaring a variable.
# In Python, a variable is created the moment you assing a first value to it.
# Moreover, in Python variables need not to be declared of a certain type.
# And they can change types by assigning new values of different types to them.

# Assign new values to the variables
a, b, c, d, e = True, False, 3.3333, 40, 'x'

# print variables again
print( a, b, c, d, e)

# Assign new values to the variables
a, b, c, d, e = True, False, True, True, False

# print variables again
print( a, b, c, d, e)

# Assign new values to the variables
a, b, c, d, e = 'Ana', 'Lucas', 'Tony', 'Liz', 'Elena'

# print variables again
print( a, b, c, d, e)

"""Casting in Python: It is used to specify a data type when creating it or updating its value. Casting is sometimes required to perform certain operations with varaibles or to send them as arguments of specific functions.

"""

a = str(100)    # x will be '3'
b = int(100)    # y will be 3
c = float(100)  # z will be 3.0

print(a, b, c)

# To get the type of a variable use the function type
print(type(a))
print(type(b))
print(type(c))

