# -*- coding: utf-8 -*-
"""python_review_2_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fjoIi5Vdoj51ODSbrh8x08OyZK7fnpD7
"""

# Rubenia Borge

thislist = ["apple", "banana", "cherry", "apple"]
print(thislist)

name = [food, dessert, hobbie]
print(name)

thislist = list(("apple", "banana", "cherry","apple")) # note the double round-brackets
print(thislist)

thislist[0]

thislist[0]

thistuple = ("apple", "banana", "cherry")
print(thistuple)

thistuple = tuple(("apple", "banana", "cherry")) # note the double round-brackets

myset = {"hips don't lie", "Mandy", "Ojos asi","Despacito"}
print(myset)

thisset = set(("apple", "banana", "cherry")) # note the double round-brackets
print(thisset)

thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
print(thisdict)

employee_dict = {
    "name": "Adam",
    "last_name": "Smith",
    "age": 25,
    "salary":50000
}

print(employee_dict)

student_dict ={
    

}
print(student_dict)